Add -n option to show changes

diff --git a/git-subst b/git-subst
--- a/git-subst
+++ b/git-subst
@@ -19,23 +19,47 @@
 
 set -e
 
-if [ -z "$1" ] ; then
-  echo "Usage: $0 search-pattern replacement-string" 1>&2
+# Display usage information and exit
+usage()
+{
+  echo "Usage: $0 [-n] search-pattern replacement-string" 1>&2
   cat <<\EOF 1>&2
+Replace the regular expression with a string.
+
+  -n Only show what replacements will be performed
 
 Examples:
-git subst old new
-git subst '\.Body' .body  # . RE character is escaped
-git subst '\<statuscode\>' statusCode  # Matches whole words only
-git subst '\.custom\(([^)]*)\)' '.\1'  # .custom(foo) becomes .foo
+  git subst old new
+  git subst '\.Body' .body  # . RE character is escaped
+  git subst '\<statuscode\>' statusCode  # Matches whole words only
+  git subst '\.custom\(([^)]*)\)' '.\1'  # .custom(foo) becomes .foo
 EOF
   exit 1
+}
+
+# Process command-line arguments
+while getopts "n" opt; do
+  case $opt in
+    n)
+      show_only=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      usage
+      ;;
+  esac
+done
+
+shift "$((OPTIND-1))"
+
+if [ -z "$1" -o -z "$2" -o -n "$3" ] ; then
+  usage
 fi
 
 # Obtain an in-place replacement option compatible with GNU and BSD sed
 if sed --quiet q /dev/null 2>/dev/null ; then
   # GNU
-   nplace=-i
+  inplace=-i
 else
   # BSD (and macOS)
   inplace='-i ""'
@@ -61,5 +85,18 @@ fi
 # A rare separation character for sed (alert; ASCII 7)
 S=$(printf '\a')
 
+if [ -n "$show_only" ] ; then
+  git stash push -q -m 'Pre git-subst stash'
+  git stash apply -q
+fi
+
+# Perform the specified replacement
 git grep --extended-regexp --null --name-only -- "$1" |
   xargs $skip_empty -0 sed $regexp_extended $inplace "s$S$1$S$2${S}g"
+
+if [ -n "$show_only" ] ; then
+  git diff 'stash@{0}'
+  git stash push -q -m 'Post git-subst stash'
+  git stash pop -q 'stash@{1}'
+  git stash drop -q
+fi
